### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by timothystewart6** [techno-tim/littlelink-server#1]
Would be nice to opt in to Google Analytics

**Comment by northportio** [comment]
Would be nice to add the option to set a meta tag to not have it indexed. See this [Google Dev Doc](https://developers.google.com/search/docs/advanced/crawling/block-indexing).

**Comment by timothystewart6** [comment]
This feature was added in https://github.com/techno-tim/littlelink-server/commit/1dc1de25142adefc9d6dab50e962aa392b4b9bad

**Comment by timothystewart6** [comment]
added button click events https://github.com/techno-tim/littlelink-server/commit/962742ced7d3398e48294c9cfea7e95940b47c9b
