### ISSUE TITLE
Demo SIte

### ISSUE THREAD

**Issue by timothystewart6** [techno-tim/littlelink-server#101]
It would be nice to generate a demo site with all available options.  This would make it easier to see supported features / themes rather than depend on my personal version of the site.

**Comment by Choubakawa** [comment]
And clean the README; It's not very clear to have all available options in the docker-compose example, we should only have your version in the README.

We could add a new paragraph with all available options in a table, or a link to a new MD file or a wiki (the wiki might be overkill).

**Comment by timothystewart6** [comment]
Thank you!  Agreed!  Or an example.env file or something.  The README is ginormous :)

**Comment by timothystewart6** [comment]
Going to close this.  The demo site will be my live site.  README has also been cleaned up.
