### ISSUE TITLE
Feature Request: Mouseover effect custom buttons

### ISSUE THREAD

**Issue by srsbsnsx** [techno-tim/littlelink-server#105]
btw: great work guys!

Feature Request: Mouseover effect for custom buttons

Requesting:
it would be nice if the mouse over effect could also be implemented for custom buttons

**Comment by timothystewart6** [comment]
Hi!  This works.  Be sure to include the variable `CUSTOM_BUTTON_ALT_TEXT`

https://github.com/techno-tim/littlelink-server/blob/master/src/components/Home/Home.js#L98

**Comment by timothystewart6** [comment]
You can see this working on my personal site too, the last link Documentation is a custom button and has the alt text
https://technotim.live/

**Comment by srsbsnsx** [comment]
Sorry for the misunderstanding. I don't mean the text of the button, I mean the brightness of the button. It dims a bit as soon as the mouse points to the button. This "effect" is also missing in your documentation button.

**Comment by timothystewart6** [comment]
Ah, sorry!  Thank you!  Will check it out!
