### ISSUE TITLE
Feature Request: Additional Links | OnlyFans

### ISSUE THREAD

**Issue by srsbsnsx** [techno-tim/littlelink-server#106]
Feature Request: Additional Links

Requesting

OnlyFans
(https://onlyfans.com/)

Something for the female users ;)

**Comment by srsbsnsx** [comment]
First of all thanks for the work! The button doesn't work for me. The other new ones work so far. Tested with the latest version on all themes.

**Comment by Choubakawa** [comment]
Maybe it's because of this

https://github.com/techno-tim/littlelink-server/blob/ec893013d9850e1127aae99f6cef3521476b8bd1/src/config.js#L358

`process.env.KEYBASE` instead of `process.env.ONLYFANS`
