### ISSUE TITLE
Visual: Email Button background

### ISSUE THREAD

**Issue by srsbsnsx** [techno-tim/littlelink-server#108]
Hey,

the background color for the emailbutton is the same as the background color of the page (dark theme).
As a result, the button is not visible. The problem only exists with the latest update.

Cheers,
Lucas

**Comment by Choubakawa** [comment]
The CSS was removed, I've opened a PR to re-add the CSS.

For custom buttons we have COLOR and TEXT_COLOR envs, should we add them for email buttons?
