### ISSUE TITLE
Having a Mastodon entry

### ISSUE THREAD

**Issue by MorpheusH3x** [techno-tim/littlelink-server#13]

**Comment by MorpheusH3x** [comment]
I would really like to contribute but there is no quick explanation of how to do so.
It would be beneficial for the project, to be honest.

**Comment by Ornias1993** [comment]
@MorpheusH3x This is just a docker container, not the actual project itself...
https://github.com/sethcottle/littlelink/tree/main/icons

**Comment by MorpheusH3x** [comment]
@Ornias1993 So should I make the PR here or on the sethcottle's one ?

**Comment by MorpheusH3x** [comment]
Should be resolve by #14

**Comment by Ornias1993** [comment]
Also on github you shouldn't close issues before PR's are merged.
You should ONLY close when PR's are merged.

**Comment by timothystewart6** [comment]
closed by https://github.com/techno-tim/littlelink-server/pull/14
