### ISSUE TITLE
Feature Request(s): Additional Links | Custom URL

### ISSUE THREAD

**Issue by rchr5880** [techno-tim/littlelink-server#160]
Feature Request(s): Additional Links | Custom URL

Hi, 

Would be really useful to be able to add a custom link to say a personal website. If you could put in a custom logo, custom label, and URL that would be brilliant. 

Thanks

**Comment by timothystewart6** [comment]
Hi!  This is already supported!  See Custom Buttons in the example!

**Comment by rchr5880** [comment]
Perfect thanks, 

I didn’t look at the example in full, I just downloaded the Docker Compose file and payed around with that.

Cheers
