### ISSUE TITLE
Add FLICKR button (request)

### ISSUE THREAD

**Issue by escaparrac** [techno-tim/littlelink-server#169]
as title says, please, could you add flickr button?

**Comment by KieranRobson** [comment]
Got the svg for this, will be up on Tuesday as I'm at a graduation tomorrow, feel free to request more and I'll do them in bulk @escaparrac

**Comment by timothystewart6** [comment]
Wow, thank you!

**Comment by KieranRobson** [comment]
@escaparrac This will be closed when the above PR is merged, feel free to request more buttons and I'll see what I can do!

**Comment by escaparrac** [comment]
@KieranRobson let me see:

- KakaoTalk (Korean #1 messaging app)
- LINE (Mainly used in Japan and Taiwan, but a big messaging app)

I made the Flickr one with the custom button thing, in case you like it:

https://hub.joaquinestevan.com/

**Comment by KieranRobson** [comment]
Please request each new item as a new issue just for tracking
