### ISSUE TITLE
Feature Request(s): Additional Links | Trakt.tv

### ISSUE THREAD

**Issue by jjjonesjr33** [techno-tim/littlelink-server#170]
Feature Request(s): Additional Links

Requesting

 - TRAKT

**Comment by KieranRobson** [comment]
This has already been done!

**Comment by jjjonesjr33** [comment]
Thanks, I did not see that it was added. 

**Suggestion**: The page where @timothystewart6 has his config shown probably needs to be updated to show all the added extras. I'm pretty sure I'm not the only one who has missed a few links that we can add now. If there was a change log or a release log to that might be easier to follow ;)

Biggest reason for all the additional links that I've submit is due to a issue with hosting this via unraid. The custom links have a limit on how many can be added. I can only get 3 links before it stops adding them. Not sure why, but that's what I've run into.

**Comment by timothystewart6** [comment]
There isn't a limit of 3 on custom links

**Comment by jjjonesjr33** [comment]
> There isn't a limit of 3 on custom links

I looked it over again, I think I fixed the issue I was having with the links not exceeding more than 3. There was a typo in one of the "`CUSTOM_BUTTON_ALT_TEXT`" ... legit was missing a " `,` "
