### ISSUE TITLE
Why Not Just Host this on github pages?

### ISSUE THREAD

**Issue by shubham399** [techno-tim/littlelink-server#18]
We can use github actions and build it and host it on github pages

**Comment by timothystewart6** [comment]
I like where you're going.  Most people using this are self-hosters but this sounds awesome too.  Let me think about this and if this is possible with the repo in it's current state.

**Comment by shubham399** [comment]
https://github.com/techno-tim/littlelink-server/pull/19

**Comment by timothystewart6** [comment]
Reference and context in https://github.com/techno-tim/littlelink-server/pull/19
