### ISSUE TITLE
Missing buttons

### ISSUE THREAD

**Issue by KierenConnell** [techno-tim/littlelink-server#197]
Looks like the Twitter & Facebook buttons don't generate currently.

Using the docker-compose example in readme.md generates a page exactly like https://technotim.live/ - With no Twitter & Facebook

https://technotim.live/ also has no Twitter or Facebook button
`view-source:https://technotim.live/` shows the Twitter & Facebook in the BUTTON_ORDER env
`"BUTTON_ORDER":"YOUTUBE,TWITCH,TWITTER,GITHUB,INSTAGRAM,LINKED_IN,DISCORD,FACEBOOK,TIKTOK,PATREON,GEAR,DOCUMENTATION,100DAYSOFHOMELAB"`

![image](https://user-images.githubusercontent.com/46445781/183624131-80d872fc-bc7d-47f3-932e-1383285d37c7.png)

**Comment by KieranRobson** [comment]
Will get this fixed tomorrow!

**Comment by timothystewart6** [comment]
Thanks, yeah, it's just the example!  I made some changes to my site but didn't update the example!

**Comment by KierenConnell** [comment]
Definitely something broken, Twitter button also missing from my own site.
And using the example config creates 'your' site, also with the missing buttons. 
Just used yours as an example because it was easiest to explain with.

**Comment by KieranRobson** [comment]
> Definitely something broken, Twitter button also missing from my own site. And using the example config creates 'your' site, also with the missing buttons. Just used yours as an example because it was easiest to explain with.

https://kieranrobson.com/ twitter generates on my own site.

**Comment by KierenConnell** [comment]
![image](https://user-images.githubusercontent.com/46445781/183858514-e00b1a5a-f24c-4075-8d6a-38d884343fc0.png)

Am I getting some trippy issue with Chrome not showing a specific button?

Turns out, yes. Yes I am.
Taken on Android.
![image](https://user-images.githubusercontent.com/46445781/183858786-fc024f55-6665-4631-8b8e-4193ad21cc09.png)

Wild...

**Comment by KieranRobson** [comment]
Could this issue be closed?

**Comment by KierenConnell** [comment]
Yup, resolved.
