### ISSUE TITLE
Nginx Reverse proxy

### ISSUE THREAD

**Issue by sysdev-isu** [techno-tim/littlelink-server#200]
Hi,

I'm using NPM and the container not loading is there any custom configuration I must add to Nginx config?

![1](https://user-images.githubusercontent.com/93702794/184479573-b7899459-cc73-4150-a325-2c04efe8c9a5.png)
![2](https://user-images.githubusercontent.com/93702794/184479575-7a1b69d4-35ac-4e03-b79f-2e5ca912c284.png)
![3](https://user-images.githubusercontent.com/93702794/184479576-0e5eae8f-2402-41b0-9a9c-9d4f5caf9e55.png)

Thanks

**Comment by KieranRobson** [comment]
When I setup I only had the top two of the let's encrypt, maybe turn those off and give it ago

**Comment by jjjonesjr33** [comment]
@sysdev-isu those are pretty much the same settings I have except I have the `cache assets` off and I'm on port 3000.

`P.S` For HSTS settings, make sure your provider for your URL supports that aka like Cloudflare to turn that feature on. 

`P.S.S` The only other thing I can advise you on is if you're hosting the Nginx Proxy Manger on the same host. In most cases it can sometimes give you problems unless you sort out your network and how everything talks/passes traffic. For myself I ended up separating Nginx Proxy Manger into it's own vm and then gave it a dedicated nic for mine to work.

**Comment by sysdev-isu** [comment]
Fixed

sorry for bothering you it is related to docker network
