### ISSUE TITLE
[BRAND REQUEST] VERO

### ISSUE THREAD

**Issue by zkvvoob** [techno-tim/littlelink-server#253]
### Please enter the brand name.

VERO

### Please enter the brand website.

https://vero.co

### Please enter the brand SVG. (If Applicable)

![VERO_Icon_Regular_White](https://user-images.githubusercontent.com/7645808/198227633-f850f4ea-06cf-4608-b81f-2c41470424f5.svg)

**Comment by zkvvoob** [comment]
Dear @timothystewart6, will you be able to spare some time to add Vero as a brand, please?

**Comment by KieranRobson** [comment]
I will get this uploaded tonight or tomorrow - I will UTC time
