### ISSUE TITLE
Custom Button Icon - not from FontAwesome?

### ISSUE THREAD

**Issue by zkvvoob** [techno-tim/littlelink-server#254]
### Buttons Relation

CUSTOM

### Bug Description

I'm not sure this is a bug, more of a question - is it possible to use a custom SVG file for a custom button? I.e. not from font-awesome? I have mapped `/usr/src/app/build/public/static`, so I can add files and have already referenced my own avatar from the local file system.

### Expected Result

Show a custom SVG icon?

**Comment by timothystewart6** [comment]
Not supported at this time, but you can give it a shot if you are mapping the local file system (also something that isn't supported).
