### ISSUE TITLE
Feature request? Adding HTML attributes to links

### ISSUE THREAD

**Issue by fr0st-beard** [techno-tim/littlelink-server#271]
Hi! Thank you so much for all the work you do getting this working with Docker and making it so easy to use. I really appreciate it.

I have a question/maybe a feature request? I'm looking to verify my name on Mastodon, and to do that you need to put this on your website: <a rel="me" href="https://mastodon.social/@username">Mastodon</a>

I was just checking to see if it's possible to add any custom HTML attributes to the links (or any custom HTML anywhere on the page, for that matter).

Thanks again!

**Comment by timothystewart6** [comment]
Hi there and thank you!  This is already supported!  If you add a mastodon link, it ill add the custom html for you!

See this https://github.com/techno-tim/littlelink-server/pull/262
