### ISSUE TITLE
[BUG REPORT] Meta attributes are undefined when not set in docker-compose

### ISSUE THREAD

**Issue by Choubakawa** [techno-tim/littlelink-server#304]
### Buttons Relation

META_TITLE, META_DESCRIPTION, META_AUTHOR, META_KEYWORDS

### Bug Description

If we do not set those variables in docker-compose, they are `undefined` in the HTML file.

```html
<meta name="keywords" content="undefined">
```

### Expected Result

HTML should be removed if the attribute is not set.

### Additional Information

We can test the variable before adding the HTML in server.js

```js
      ${
        runtimeConfig.META_KEYWORDS
          ? `<meta name="keywords" content="${runtimeConfig.META_KEYWORDS}" />`
          : ''
      }
```

**Comment by timothystewart6** [comment]
I fixed one, didn't realize you mentioned all 3 in this issue, and mentioned the same thing in my PR.  Will try to get the rest this week!
