### ISSUE TITLE
Background Color

### ISSUE THREAD

**Issue by matthewshammond** [techno-tim/littlelink-server#308]
I apologize if this has been answered. I have done my due diligence researching and looking at where exactly to change the default background color to a different background color. I've seen the posts about changing the background to an image; however, I just want to change the background color and I'm not too familiar with css.  Which file do I edit to change the default background color?

**Comment by matthewshammond** [comment]
I found my issue. I had been editing the correct file. I had to flush my cache so when it reloaded the page it was pulling fresh. Background color updated and is working.  Apologies for the issue.

**Comment by timothystewart6** [comment]
No worries!  Glad you figured it out!
