### ISSUE TITLE
Umami's TRACKER_SCRIPT_NAME not respected

### ISSUE THREAD

**Issue by eitchtee** [techno-tim/littlelink-server#372]
### Buttons Relation

N/A

### Bug Description

Unable to use a custom script set using umami's enviroment variable [`TRACKER_SCRIPT_NAME`](https://umami.is/docs/environment-variables).

By setting `UMAMI_APP_URL` the end of the url is always `/umami.js` on the generated site.

### Expected Result

A way to set a custom script name or a way to set the full url used by littlelink

Something like `{ UMAMI_APP_URL }/{UMAMI_SCRIPT_NAME}.js` or `{ UMAMI_SCRIPT_URL }`.

**Comment by timothystewart6** [comment]
Hey!  I like the suggestion however in order to preserve compatibility I can't change how it currently works otherwise it would break someone's code the next time the pull a new image.

Out of curiosity, why can't you just set  `TRACKER_SCRIPT_NAME`  to `umami.js` ?

**Comment by eitchtee** [comment]
> Out of curiosity, why can't you just set `TRACKER_SCRIPT_NAME` to an empty string? `''`

You can, but `TRACKER_SCRIPT_NAME` is a used to bypass adblocking, since umami.js is commonly blocked.

> Hey! I like the suggestion however in order to preserve compatibility I can't change how it currently works otherwise it would break someone's code the next time the pull a new image.

Perhaps have a default and a override? For example, if `UMAMI_SCRIPT_NAME` is set the script tag uses it, if not, `umami.js` is set as a default, I believe that would preserve backwards compatibility and solve the problem.

**Comment by timothystewart6** [comment]
Yeah, that was the other option I was going to type out but then had the idea of just using blank :)  This shouldn't take too long, I can probably get to it this weekend!

**Comment by timothystewart6** [comment]
So, I think we're settling on this ?

```env
UMAMI_APP_URL=https://example.com/js/
UMAMI_SCRIPT_NAME=script.js
```

**Comment by eitchtee** [comment]
A mentioned on the PR, the` /js/` dir is removed on newer versions, but I'm good with the changes mentioned.

Worth noting that this will break older installations, but I don't see how to avoid that:

Umami v1 used `umami.js`, the newer version (v2) uses `script.js` as mentioned on #395, and both versions support the custom script name, so there isn't a safe default to use, as some people may choose to not upgrade to v2 or aren't aware of the update.

I'd vote for keeping umami.js as the default, since upgrading to v2 is not as simples as changing versions, and allowing to override the script name if needed as discussed with a warning about this on the docs.

**Comment by timothystewart6** [comment]
This was closed by https://github.com/techno-tim/littlelink-server/pull/395
