### ISSUE TITLE
srcset not updated with AVATAR_URL

### ISSUE THREAD

**Issue by Choubakawa** [techno-tim/littlelink-server#4]
The attribute `srcset` of the avatar is not updated with the env var `AVATAR_URL`, on some device the default image will be display.

**Possible fix:**

Adding an env var `AVATAR_2X_URL` to update the attribute would fix the issue or using `AVATAR_URL` to update `srcset` (but we will lose the utility of `srcset`).

**Comment by timothystewart6** [comment]
Thank you!  Let me work on a fix.  I think I will go with your recommendation of `AVATAR_2X_URL `

**Comment by timothystewart6** [comment]
Fixed by https://github.com/techno-tim/littlelink-server/commit/b06bb9443f23b5215fd14475b457728086461cf2
