### ISSUE TITLE
Matamo analytics support?

### ISSUE THREAD

**Issue by samip5** [techno-tim/littlelink-server#41]
Please add support for Matamo (https://matomo.org).

**Comment by timothystewart6** [comment]
I am happy to write this integration but I have no easy way of testing it, outside of hosting/creating my own account

**Comment by samip5** [comment]
This is the code for Matamo:

```
<!-- Matomo -->
<script type="text/javascript">
    var _paq = window._paq || [];
    /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    (function () {
        var u = "//samip.fi/matomo/";
        _paq.push(['setTrackerUrl', u + 'matomo.php']);
        _paq.push(['setSiteId', '1']);
        var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
        g.type = 'text/javascript';
        g.async = true;
        g.defer = true;
        g.src = u + 'matomo.js';
        s.parentNode.insertBefore(g, s);
    })();
</script>
<!-- Image Tracker-->
<img src="https://samip.fi/matomo/matomo.php?idsite=1&amp;rec=1" style="border:0" alt=""/>
<!-- End Matomo Code -->
```


SiteID and the URL to the matomo instance is the most things it would need.

**Comment by kenjibailly** [comment]
Any progress on this? :)

**Comment by timothystewart6** [comment]
@kenjibailly  nope but PRs are welcome!  In my experience, the person that cares about it most will add this feature.

**Comment by kenjibailly** [comment]
I def want to look on how to implement it, but I'm just a hobbyist coder and have no idea how you link your variables to docker. Some pointers would help me out try to make it happen :)

**Comment by kenjibailly** [comment]
I figured it out and made a pull request for this here: #111

**Comment by timothystewart6** [comment]
closed by https://github.com/techno-tim/littlelink-server/pull/112
