### ISSUE TITLE
[BRAND REQUEST] X (the "new" twitter)

### ISSUE THREAD

**Issue by LukasL28** [techno-tim/littlelink-server#467]
### Please enter the brand name.

X

### Please enter the brand website.

https://twitter.com

### Please enter the brand SVG. (If Applicable)

https://cdn.cms-twdigitalassets.com/content/dam/about-twitter/x/brand-toolkit/logo-black.png.twimg.2560.png

https://about.twitter.com/en/who-we-are/brand-toolkit

**Comment by LukasL28** [comment]
I would suggest adding this as a "new" brand to keep the old twitter logo as a legacy option

**Comment by timothystewart6** [comment]
Agreed, it's a "new brand" so we wouldn't replace the old.

**Comment by KieranRobson** [comment]
Been meaning to add this, will be added tomorrow, sometime BST time

**Comment by KieranRobson** [comment]
Thanks for the suggestion @LukasL28, If you come across any other ideas for sites or apps to add to the repo, let us know and we can add them, the only real stipulation is a svg logo. 

Feel free to request even if you do not have a svg logo available and we might be able to find one!
