### ISSUE TITLE
Generic Links

### ISSUE THREAD

**Issue by timothystewart6** [techno-tim/littlelink-server#5]
support for generic text based buttons

**Comment by timothystewart6** [comment]
The easiest was is to add an option for ~3 buttons (like email) that render if an env is passed in.

**Comment by Cur50r** [comment]
ah didn't see this, I have raised a PR for the short-term email text issue

**Comment by Choubakawa** [comment]
An idea:

Having 2 envs LINKS_HREF and LINKS_TEXT with splittable string.

```javascript
if (LINKS_HREF && LINKS_TEXT) {
    var hrefs = LINKS_HREF.split(',');
    var texts = LINKS_TEXT.split(',');
    if (hrefs.length == texts.length)
    for (let index = 0; index < hrefs.length; index++) {
        //need a generic icon
        var button = document.createElement('<a class="button button-default" href="' + hrefs[index] + '" target="_blank" rel="noopener"><img class="icon" src="icons/generic_link.svg" alt="Generic Icon">' + texts[index] + '</a><br>');
        //need to have an empty div with id 'generics' in the template
        document.getElementById('generics').appendChild(button);
    }
}
```

Unlimited links for unlimited power lol

**Comment by kenjibailly** [comment]
Would love this to be added, so I can add all my website links. The only thing I'm missing! :D

**Comment by timothystewart6** [comment]
Soon!  Just need 30 min to crank it out :)   Maybe tonight!

**Comment by timothystewart6** [comment]
@Choubakawa @kenjibailly @Cur50r  https://github.com/techno-tim/littlelink-server/pull/61   Should be available now!
