### ISSUE TITLE
[Request] Please move to publishing semver releases

### ISSUE THREAD

**Issue by chrede88** [techno-tim/littlelink-server#532]
### Buttons Relation

n/a

### Bug Description

n/a

### Expected Result

n/a

### Additional Information

I really like this project, but it would be so much better if you started publishing releases. As it stands I'm forced to lock my update automations to the container digest, which changes on every push.

**Comment by timothystewart6** [comment]
See https://github.com/techno-tim/littlelink-server/issues/76

**Comment by timothystewart6** [comment]
This was discussed in the above issue.  I totally understand why I should use semver but at the same time, pinning to SHA gives you the same result as pinning to a container tag and also the same amount of work on your part.  Curious if I am missing an edge case?

**Comment by chrede88** [comment]
You're an absolutely right, I'm also pinning to the sha hash and it works. Renovate picks up any updates to the image. I guess it's really an issue on my part. I'm for now updating my cluster manually, and because your automation is building a new image on every push, I'm updating this quite often. I guess I hoping that moving to releases would mean a less frequent update cycle.
I understand I should probably just get my act together and implement fluxcd or something similar.

**Comment by timothystewart6** [comment]
Ha!  No worries at all, and yes, you are right, even if I did move to semver I would still release it on ever commit to `main`.  I don't like sitting on releases and I have CI that tests quite a bit so that I can release with confidence!
