### ISSUE TITLE
Custom Favicon and Button Text for Ghost

### ISSUE THREAD

**Issue by leslietech** [techno-tim/littlelink-server#535]
I find it challenging having to explain each time to folks what the Ghost in my links site is. 

With that in mind, is there an option to set a custom favicon as well as custom button label/text for Ghost?

If not, does a custom button allow one to add a favicon as well as custom button label/text? If "yes", I cannot figure out from the documentation how to add a custom button.

Note: I appreciate this project.

**Comment by timothystewart6** [comment]
Hey!  I know what you mean.  We have custom button support which supports custom buttons, text, colors, and description!  You can find it in the example!  I use it also on my links site!
