### ISSUE TITLE
[BUG REPORT] <Concise description of the bug>

### ISSUE THREAD

**Issue by ta1kun** [techno-tim/littlelink-server#542]
### Buttons Relation

responsive bug in mobile

### Bug Description

As u can see in the image exist a left margin that in mobile view push to the right the page.
![IMG_20240101_205105](https://github.com/techno-tim/littlelink-server/assets/22143723/7de6e44e-d78c-44ed-b1a0-fdfb82c46f9d)

### Expected Result

Left margin should be removed. The page must be centered

**Comment by Choubakawa** [comment]
Related to #78

**Comment by timothystewart6** [comment]
closing as duplicate
