### ISSUE TITLE
Suggestion for img hosting

### ISSUE THREAD

**Issue by madvip3r** [techno-tim/littlelink-server#57]
Because Firefox is unhappy with the image being hosted on Twitter (because of tracking component), you can also use image sharing platform at Imgur.com. 

Maybe a suggestion if possible: hosting image from inside docker container, with bind volume as a permanent storage.

**Comment by timothystewart6** [comment]
Hi!  Thanks for the workaround.  For now we are going to keep the stateless nature of this container and not bind mount volumes.  We'll see how we can improve this though in the future!
