### ISSUE TITLE
EMail ALT Text

### ISSUE THREAD

**Issue by WhyAydan** [techno-tim/littlelink-server#6]
Hey, Looks like the email ALT text has been statically set to 'hello@littlelink.io'

Fixed it by manually setting it in the index.html but for future if you do any updates :)

Aydan

**Comment by madvip3r** [comment]
If possible, it would be nice, to add in line [156](https://github.com/techno-tim/littlelink-server/blob/0ff4b782dcda81e1f1a52ad1c58b2deb1dfc1fae/www/index.html#L156) and [160](https://github.com/techno-tim/littlelink-server/blob/0ff4b782dcda81e1f1a52ad1c58b2deb1dfc1fae/www/index.html#L160) a configurable placeholder as is done for links.

**Comment by Anthonyyp** [comment]
@WhyAydan came to post about this exactly - am new at docker - how do you access the index.html file within a docker container like this?

**Comment by madvip3r** [comment]
@Anthonyyp the problem with editing index.html inside docker container is that this change will only last as long docker container lives. At the next restart of the container (that is, next change) it will be reverted back to original state.

**Comment by WhyAydan** [comment]
@Anthonyyp Hey so you need to terminal in the Docker Container then cd into www. 
Once in there you need to type vi index.html
Use the arrow keys to find the email place holder once you found it press the i key. Edit the field and then press CTRL+C followed by :wq

Let me know if you need more help

**Comment by Anthonyyp** [comment]
That's what I thought. I'm new to docker and containerization.

**Comment by Anthonyyp** [comment]
> @Anthonyyp the problem with editing index.html inside docker container is that this change will only last as long docker container lives. At the next restart of the container (that is, next change) it will be reverted back to original state.

That's what I thought - am new to docker and containerization.



> @Anthonyyp Hey so you need to terminal in the Docker Container then cd into [www](http://www).
> Once in there you need to type vi index.html
> Use the arrow keys to find the email place holder once you found it press the i key. Edit the field and then press CTRL+C followed by :wq
> 
> Let me know if you need more help

I'm SSH'd into the machine running it and have been combing through directories and I can not find where the www folder is. I must be overlooking something.

**Comment by madvip3r** [comment]
@Anthonyyp you can use docker command to "ssh" into the container:
`docker exec -it CONTAINER_ID bash`

Replace CONTAINER_ID with name or id of container. When you want to get back, you just enter `exit` or Ctrl-D.

**Comment by timothystewart6** [comment]
This has been fixed by https://github.com/techno-tim/littlelink-server/commit/77c5cfba2a57ea55e7220e19c81a5ed8de2b14ef

It should now render your email within the button!  Sorry about that and thanks for reporting it!
