### ISSUE TITLE
[BUG REPORT] only 2 custom buttons will be shown

### ISSUE THREAD

**Issue by mcasviper** [techno-tim/littlelink-server#602]
### Buttons Relation

CUSTOM_BUTTON

### Bug Description

I have 3 CUSTOM_BUTTONs configured but only the first 2 will be shown. The third one is missing.

### Expected Result

alle comma separated custom buttons will be shown.

**Comment by timothystewart6** [comment]
Can you please share you configuration?  I have 4 and they are working

https://links.technotim.live/

**Comment by mcasviper** [comment]
This is the part for the custom buttons:
`      - BUTTON_ORDER=LINKED_IN,XING,CREDLY2,CREDLY,BADGR,GITHUB,EMAIL,TELEGRAM
#      - PAYPAL=https://www.paypal.me/user
#      - SIGNAL=https://signal.org/
      - CUSTOM_BUTTON_TEXT=Credly,Credly Business,Badgr
      - CUSTOM_BUTTON_URL=https://www.credly.com/users/marcus-asshauer,https://www.credly.com/users/marcus-asshauer.33b5ba2a,https://api.eu.badgr.io/public/collections/08cefb1348104b7e9c6935960fc2e3b9
      - CUSTOM_BUTTON_COLOR=#000000,#000000
      - CUSTOM_BUTTON_TEXT_COLOR=#ffffff,#ffffff
      - CUSTOM_BUTTON_ALT_TEXT=Credly Badges,More Creadly Badges,Badgr Badges
      - CUSTOM_BUTTON_NAME=CREDLY,CREDLY2,BADGR
      - CUSTOM_BUTTON_ICON=fas certificate,fas certificate,fas certificate`

**Comment by timothystewart6** [comment]
You only have 2 colors and 3 buttons 😅
