### ISSUE TITLE
Custom Icons for Custom Buttons

### ISSUE THREAD

**Issue by timothystewart6** [techno-tim/littlelink-server#62]
Now that we have Custom Buttons https://github.com/techno-tim/littlelink-server/pull/61 

Custom Icons would be nice too.  I am thinking of using `fontawesome` or `material` icons.

**Comment by kenjibailly** [comment]
SVG's are currently used I see, those work as well for me at least!
Would love to see this happening!

**Comment by Choubakawa** [comment]
I wanted to try with FontAwesome but I'm not sure if it's a good way to implement it.
I've created a PR.
