### ISSUE TITLE
[BRAND REQUEST] Untappd and Google Maps widget

### ISSUE THREAD

**Issue by barbariska108** [techno-tim/littlelink-server#654]
### Please enter the brand name.

Untappd
Google Maps

### Please enter the brand website.

https://untappd.com/
https://www.google.com/maps

### Please enter the brand SVG. (If Applicable)

![image](https://github.com/user-attachments/assets/a4555a3b-048b-4df9-aef8-3d8ecbadf7e7)
![image](https://github.com/user-attachments/assets/282b9f4f-6cc5-4391-a6a7-f98c9fbc02a1)

**Comment by Choubakawa** [comment]
Hello, https://untappd.com/ already exists under the var: `UNTAPPD`.

**Comment by barbariska108** [comment]
> Hello, https://untappd.com/ already exists under the var: `UNTAPPD`. 

Tnx! Didn't check this one fully.
