### ISSUE TITLE
Enable / disable to open a certain link in the same window instead of new tab

### ISSUE THREAD

**Issue by kenjibailly** [techno-tim/littlelink-server#72]
So basically I'm running 2 containers right now to have a button link to the second container with a bunch of other buttons.
For reference check NFT button:
https://links.mindglowing.art

How the problem is that it's very unnecessary that my NFT button on my main container opens a new tab since it's just opening another link container where there's a button to go back to the main container, this last button also opens a new tab.

Is it possible to turn on "open in same window" on specific link buttons?

**Comment by timothystewart6** [comment]
sounds doable!

**Comment by timothystewart6** [comment]
After thinking about this some more, I think this would be a global setting. meaning if you enable it, it would open all buttons in the same window, rather than a new one.  Otherwise we will end up with 2x variables.
