### ISSUE TITLE
environmental variable for meta tags 

### ISSUE THREAD

**Issue by Anthonyyp** [techno-tim/littlelink-server#8]
nowhere in the docker-compose.yml to modify the meta tags on the html page leaving the link previews to read "LittleLink - Find us online!"
>  <meta charset="utf-8">
>   <title id="meta-title">LittleLink</title>
>   <meta id="meta-description" name="description" content="Find us online!">
>   <meta id="meta-author" name="author" content="Seth Cottle">

**Comment by Anthonyyp** [comment]
> nowhere in the docker-compose.yml to modify the meta tags on the html page leaving the link previews to read "LittleLink - Find us online!"
> 
> > <title id="meta-title">LittleLink</title>

**Comment by timothystewart6** [comment]
This was fixed by https://github.com/techno-tim/littlelink-server/commit/937647d04ef800e3525d4af8da2930033efed0bd

Let me know if you still have issues!  Thank you for reporting it!
