### ISSUE TITLE
https not supported

### ISSUE THREAD

**Issue by silentpiranha** [techno-tim/littlelink-server#80]
Access via https is not possible.
Https should be available

I want to expose this service with KEMP and Kemp needs https support to work.

**Comment by timothystewart6** [comment]
Hi.  You will need to put a reverse proxy in front of this.  If you're looking for a guide on how to do that you can follow this https://docs.technotim.live/posts/traefik-portainer-ssl/ or many other guides on how to install and configure a reverse proxy.

**Comment by silentpiranha** [comment]
Hi 
I use Kemp as reverse proxy service. It needs https support at the endpoint. As all traffic is encrypted. 
I could switch endpoint encryption off. But then one of my services is not available, as it only provides https

**Comment by timothystewart6** [comment]
Hi.  The job of most reverse proxies it to provide a single proxy for common tasks and features like transport encryption.  I haven't used kemp before, but have use many other load balancers and revers proxies and typically that is where you terminate your certificates.
