### ISSUE TITLE
Page loads for a second and then changes to "Undefined" in firefox

### ISSUE THREAD

**Issue by TabinAhmad** [techno-tim/littlelink-server#84]
I have it setup and it works fine on Edge, Chrome, and Android phones, but when loading via Firefox, the site will load everything for a second before just leaving the profile picture and "undefined"
Loading:
![image](https://user-images.githubusercontent.com/82327041/151738216-be138a22-812e-4646-b8ec-432fcf00d9fa.png)

After Loading in Firefox:
![image](https://user-images.githubusercontent.com/82327041/151738235-e0789508-c2f8-4262-8bd7-63691692af60.png)

In Chrome it works fine:
![image](https://user-images.githubusercontent.com/82327041/151738253-7dbe28cc-e768-4da9-a5b7-8acea22eac8e.png)

Not what's causing the issue (running through a reverse proxy with SSL certs and everything working properly)

Folks on iPhone, Safari and Aloha are reporting "Undefined" as well.

Thoughts?

**Comment by timothystewart6** [comment]
Sorry about that.  I see what's going on.  Fixed by https://github.com/techno-tim/littlelink-server/commit/9f3bde8324afac1502fc9f455479c315f2096be1  rolling out now

**Comment by TabinAhmad** [comment]
Nothing to be sorry about at all. Fix works like a charm!!  Thank you for building this as well!
