### ISSUE TITLE
Feature Request(s): Additional Links

### ISSUE THREAD

**Issue by jjjonesjr33** [techno-tim/littlelink-server#85]
Even though we have custom links there is a limit on a max of 3 before it will not take any more.

Requesting

 - CASHAPP
 - AMAZON_AFFILATE_LINK
 - AMAZON_WISHLIST
 - STREAMLABS_TIP
 - STREAMELEMENTS_TIP
 - TEESPRING
 - DESIGNBYHUMANS

**Comment by timothystewart6** [comment]
Hey thanks!  Any way you can break these up into individual issues so that they can be worked on separately?  Also, there shouldn't be a limit on custom links, it should be unlimited, that is the max of what you can fit in an env variable

**Comment by timothystewart6** [comment]
Thank you!

**Comment by jjjonesjr33** [comment]
Your welcome 😄 totally sorry for the github email spam.
