### ISSUE TITLE
Feature Request(s): Link Generated Cards - With Pictures

### ISSUE THREAD

**Issue by jjjonesjr33** [techno-tim/littlelink-server#86]
Best way to example would be an example. But these would have auto links that generate a photo when posted on social media sites like facebook, twitter, ect ...

What I would like to see
![image](https://user-images.githubusercontent.com/29973406/152889014-4b3134e8-c22b-4e4f-84f3-e1d29a8253b4.png)

VS what we have now
![image](https://user-images.githubusercontent.com/29973406/152889044-9d157c3e-28fa-440e-b412-6554b14f5ba6.png)

If I am not mistaken when I did the first picture from back in the day I ripped the code that was used/injected from my old Ghost blog. I might be able to replicate that again. The goal would be making it dynamic for users to key into just like how you do the links.

**Comment by Choubakawa** [comment]
We could add these meta tags to enhance the generated card

```html
<meta property="og:site_name" content="${runtimeConfig.OG_SITE_NAME}" />
<meta property="og:title" content=“${runtimeConfig.OG_TITLE}" />
<meta property="og:description" content="${runtimeConfig.OG_DESCRIPTION}" />
<meta property="og:url" content="${runtimeConfig.OG_URL}" />
<meta property="og:type" content="siteweb" />
<meta property="og:image" content="${runtimeConfig.OG_IMAGE}" />
<meta property="og:image:secure_url" content="${runtimeConfig.OG_IMAGE}" />
<meta property="og:image:width" content="${runtimeConfig.OG_IMAGE_WIDTH}" />
<meta property="og:image:height" content="${runtimeConfig.OG_IMAGE_HEIGHT}" />
<meta property="twitter:card" content="${runtimeConfig.TWITTER_CARD}" />
<meta property="twitter:image" content="${runtimeConfig.TWITTER_IMAGE}" />
<meta property="twitter:site" content="${runtimeConfig.TWITTER_SITE}" />
```

**Comment by jjjonesjr33** [comment]
Need to re-open this issue. @Choubakawa , @timothystewart6 found two metadata fields that we were missing when I ran a social media check.

`twitter:title`
`twitter:description`

![image](https://user-images.githubusercontent.com/29973406/181626846-7a1c3870-adfa-48c9-a5f4-5b0f16b6d622.png)

**Comment by Choubakawa** [comment]
I didn't add `twitter:title` and `twitter:description` because if the 2 tags are missing it will use `og:title` or `og:description` (see [https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup)).


If you think it's better to use `twitter:title` or `twitter:description`, let's open a new issue :)
