### ISSUE TITLE
Feature Request(s): Additional Links | DESIGNBYHUMANS

### ISSUE THREAD

**Issue by jjjonesjr33** [techno-tim/littlelink-server#93]
Feature Request(s): Additional Links

Requesting

 - DESIGNBYHUMANS

**Comment by jjjonesjr33** [comment]
@KieranRobson svg link for you - [Design By Humans Artist Svg](https://cdn.designbyhumans.com/resources/badge/v2/black-flat-600.svg)

**Comment by KieranRobson** [comment]
Awesome, will get this uploaded on friday, been a bit busy today and have graduation tomorrow!

**Comment by jjjonesjr33** [comment]
> Awesome, will get this uploaded on friday, been a bit busy today and have graduation tomorrow!

Awesome! Thank you! 

P.s Also don't know if your referring to your graduation and if it is, congratz!? 😄
