### ISSUE TITLE
Visual: Ghost Button background 

### ISSUE THREAD

**Issue by gitcedric** [techno-tim/littlelink-server#99]
Hey,

the background color for the ghost button is the same as the default background color of the page (#fff).
As a result, the button is not visible. 

Thanks,
Cedric

**Comment by Choubakawa** [comment]
I did some tests:
<details>
  <summary>Current light/dark theme:</summary>
 
![current_light](https://user-images.githubusercontent.com/30017832/155003360-442eab0b-3e39-48df-a9c4-72d28f1d5b06.png)
![current_dark](https://user-images.githubusercontent.com/30017832/155003364-871da939-8c3f-4b0c-9e8a-1750b6eb8e40.png)
</details>

<details>
  <summary>If we change the background color for the light theme:</summary>

![new_background_color](https://user-images.githubusercontent.com/30017832/155004065-24cb9e59-f36e-439d-84c6-95af9e132ef3.png)
</details>


<details>
  <summary>If we add border to buttons with a white background:</summary>

![dark_border](https://user-images.githubusercontent.com/30017832/155004249-dd133e8d-069c-40d8-a43c-5e28e71543bc.png)
![light_border](https://user-images.githubusercontent.com/30017832/155004251-54e6429a-7a73-42ed-af2b-c40c7e73d53c.png)
</details>


Which one is better, the broken white or with borders?

**Comment by gitcedric** [comment]
Personally I’d go with the second option, but I’m kinda worried if this is the best option for accessibility (color blindness)

**Comment by Choubakawa** [comment]
I prefer the second option too, should we wait for more feedback? @timothystewart6?

**Comment by timothystewart6** [comment]
I do think option 2 fails the accessibility contrast ratio from the foreground to the back ground.  I think we should probably outline the button.  To keep it simple, I think we should just use a `#292929` border on all buttons that fail the 3:1 ratio when in light mode and no need to add it to the dark mode versions.  Thank you for looking into this!
